config/routes.rb
Rails.application.routes.draw do
  
  # 顧客側のパス
  devise_for :customers, path: 'customers',
  controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
    passwords: 'public/passwords'
  }
  
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    
    delete '/cart_items/all' => 'cart_items#destroy_all' # カート内商品全削除
    
    # 注文情報確認画面、注文完了画面
    get '/orders/confirm' => 'orders#confirm'
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#complete'
    
    # 情報入力画面での配送先登録用のアクション
    post '/orders/create_address' => 'orders#create_address' 
    
    # 顧客の退会確認画面、退会処理（ステータスの更新）
    get '/customers/withdrawal' => 'customers#withdrawal'
    patch '/customers/withdrawal' => 'customers#destroy'
    
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:index, :create, :new, :show]
    resources :customers, only: [:show, :edit, :update]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  end
  
  # 管理者側のパス
  devise_for :admins, path: 'admin',
  controllers: {
    sessions: 'admin/sessions',
    registration: 'admin/registrations',
    passwords: 'admin/passwords'
  }
    
  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end  
  
end

app/models/item.rb
class Item < ApplicationRecord
  
  belongs_to :genre
  has_many :order_details
  has_many :cart_items
  
  with_options presence: true do
    validates :image
    validates :name
    validates :introduction
    validates :price
    validates :is_active
  end
  
  attachment :image
  enum is_active: { 販売中: 1, 販売停止中: 2 }
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @items = Item.page(params[:page]).reverse_order
  end
  
  def new
    @item = Item.new
  end
  
  # 商品データの保存
  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = '商品データを保存しました！'
      redirect_to admin_item_path(@item)
    else
      flash[:danger] = '内容に不備があります！'
      render :new
    end  
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  # 商品データの更新
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:success] = '編集内容を保存しました！'
      redirect_to admin_item_path(@item.id)
    else
      flash[:danger] = "内容に不備があります！"
      render :edit
    end  
  end
  
  # 商品データのストロングパラメータ
  private
  
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
  
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row mb-4">
    <h1>商品編集</h1>
  </div>
  <div class="row mb-4">
    <div class="mx-auto">
    <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch, local: true do |f| %>
      <div class="form-group row">
        <label class="col-sm-3">商品画像</label>
        <div class="col-sm-9">
          <%= f.attachment_field :image %>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-3">商品名</label>
        <div class="col-sm-9">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-3">商品説明</label>
        <div class="col-sm-9">
          <%= f.text_area :introduction, class: "form-control", rows: "3" %>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-3">ジャンル</label>
        <div class="col-sm-9">
          <%= f.select :genre_id, Genre_all, :id, :name, include_blank: "--選択してください--", class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-3">税抜価格</label>
        <div class="col-sm-8">
          <%= f.text_field :price, class: "form-control" %>
        </div>
        <div class="col-sm-1">円</div>
      </div>
      <div class="form-group row">
        <label class="col">販売ステータス</label>
        <div class="col">
          <div class="form-check form-check-inline">
            <label>
              <%= f.radio_button :is_active, :販売中, class: "form-check-input" %>販売中
            </label>
          </div>
          <div class="form-check form-check-inline">
            <label>
              <%= f.radio_button :is_active, :販売停止中, class: "form-check-input" %>販売停止中
            </lavel>
          </div>
        </div>
      </div>
      <div class="form-group text-center">
        <%= f.submit "変更を保存", class: "btn btn-success mb-2" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row mb-4">
    <h1 class="col">商品一覧</h1>
    <%= link_to new_admin_item_path do %>
      <div class="row">
        <span class="fas fa-plus-circle fa-3x"></span>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col">
      <table class="table table-hover">
        <thead class="thead-light">
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td>
                <%= item.id %>
              </td>
              <td>
                <%= link_to admin_item_path(item) do %>
                  <%= item.name %>
                <% end %>
              </td>
              <td>
                <%= (item.price).to_s(:delimited) %>
              </td>
              <td>
                <%= item.genre.name %>
              </td>
              <td>
                <%= item.is_active %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row mb-4">
    <h1>商品新規登録</h1>
  </div>
  <div class="row mb-4">
    <div class="mx-auto">
    <%= form_with model: @item, url: admin_items_path, local: true do |f| %>
      <div class="form-group row">
        <label class="col-sm-3">商品画像</label>
        <div class="col-sm-9">
          <%= f.attachment_field :image %>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-3">商品名</label>
        <div class="col-sm-9">
          <%= f.text_field :name, class: "form-control", placeholder: "商品名" %>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-3">商品説明</label>
        <div class="col-sm-9">
          <%= f.text_area :introduction, class: "form-control", rows: "3", placeholder: "ここに説明文を記述します" %>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-3">ジャンル</label>
        <div class="col-sm-9">
          <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択してください--", class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-3">税抜価格</label>
        <div class="col-sm-8">
          <%= f.text_field :price, class: "form-control", placeholder: "1000" %>
        </div>
        <div class="col-sm-1">円</div>
      </div>
      <div class="form-group row">
        <label class="col">販売ステータス</label>
        <div class="col">
          <div class="form-check form-check-inline">
            <label>
              <%= f.radio_button :is_active, :販売中, class: "form-check-input"  %>販売中
            </label>
          </div>
          <div class="form-check form-check-inline">
            <label>
              <%= f.radio_button :is_active, :販売停止中, class: "form-check-input" %>販売停止中
            </lavel>
          </div>
        </div>
      </div>
      <div class="form-group text-center">
        <%= f.submit "新規登録", class: "btn btn-success mb-2" %>
      </div>
    <% end %>
    </div>
  </div>†
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row mb-4">
    <h1>商品詳細</h1>
  </div>
  <div class="row mb-4 mx-auto w-75">
    <div class="col-sm">
      <%= attachment_image_tag @item, :image, :fill, 220, 250 %>
    </div>
    <div class="col-sm">
      <div class="row">
        <label class="col-sm-6">商品名</label>   
        <div class="col-sm-6">
          <%= @item.name %>
        </div>
      </div>
      <div class="row">
        <label class="col-sm-6">商品説明</label>   
        <div class="col-sm-6">
          <%= @item.introduction %>
        </div>
      </div>
      <div class="row">
        <label class="col-sm-6">ジャンル</label>   
        <div class="col-sm-6">
          <%= @item.genre.name %>
        </div>
      </div>
      <div class="row">
        <label class="col-sm-6">税込価格<br>(税抜価格)</label>   
        <div class="col-sm-6">
          <%= (1.1 * @item.price).floor.to_s(:delimited) %>(<%= (@item.price).floor.to_s(:delimited) %>)  円
        </div>
      </div>
      <div class="row">
        <label class="col-sm-6">販売ステータス</label>   
        <div class="col-sm-6">
          <%= @item.is_active %>
        </div>
      </div>
    </div>
  </div>
  <div class="row text-center">
    <div class="col">
      <%= link_to edit_admin_item_path(@item) do %>
        <span class="btn btn-success mb-2">編集する</span>
      <% end %>
    </div>
  </div>
</div>