config/routes.rb
Rails.application.routes.draw do
  
  # 顧客側のパス
  devise_for :customers, path: 'customers',
  controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
    passwords: 'public/passwords'
  }
  
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    
    delete '/cart_items/all' => 'cart_items#destroy_all' # カート内商品全削除
    
    # 注文情報確認画面、注文完了画面
    get '/orders/confirm' => 'orders#confirm'
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#complete'
    
    # 情報入力画面での配送先登録用のアクション
    post '/orders/create_address' => 'orders#create_address' 
    
    # 顧客の退会確認画面、退会処理（ステータスの更新）
    get '/customers/withdrawal' => 'customers#withdrawal'
    patch '/customers/withdrawal' => 'customers#destroy'
    
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:index, :create, :new, :show]
    resources :customers, only: [:show, :edit, :update]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  end
  
  # 管理者側のパス
  devise_for :admins, path: 'admin',
  controllers: {
    sessions: 'admin/sessions',
    registration: 'admin/registrations',
    passwords: 'admin/passwords'
  }
    
  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end  
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  with_options presence: true do
    validates :last_name
    validates :last_name_kana
    validates :first_name
    validates :first_name_kana
    validates :address
    validates :telephone_number
    validates :is_active
  end
  
  enum is_active: { 有効: 1, 退会: 2 }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @customers = Customer.page(params[:page]).reverse_order
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      if @customer.is_active == "有効"
        @customer.update(is_valid: true)
        flash[:success] = '会員情報の更新に成功しました！'
        redirect_to admin_customer_path(@customer)
      elsif @customer.is_active == "退会"
        @customer.update(is_valid: false)
        flash[:success] = '会員情報の更新に成功しました！'
        redirect_to admin_customer_path(@customer)
      end  
    else  
      flash[:danger] = '内容に不備があります！'
      render :edit
    end
  end
  
  # 会員情報の更新ストロングパラメータ
  private
  
  def customer_params
    params.require(:customer).permit(
      :last_name, 
      :first_name, 
      :last_name_kana, 
      :first_name_kana,
      :email,
      :encrypted_password,
      :postal_code,
      :address,
      :telephone_number,
      :is_active
    )
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row mb-4">
    <h1>
      <%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集
    </h1>
  </div>
  <div class="row mb-4">
    <div class="w-75">
      <%= form_with model: @customer, url: admin_customer_path, local: true do |f| %>
        <div class="row">
          <label class="col-sm-4 col-form-label"><%= f.label :会員id %></label>
          <div class="col-sm-8">
            <%= @customer.id %>
          </div>
        </div>
        <div class="row">
          <label class="col-sm-4 col-form-label"><%= f.label :氏名 %></label>
          <div class="col-sm-4">
            <%= f.text_field :last_name, class: "form-control" %>
          </div>
          <div class="col-sm-4">
            <%= f.text_field :first_name, class: "form-control" %>
          </div>
        </div>
        <div class="row">
          <label class="col-sm-4 col-form-label"><%= f.label :フリガナ %></label>
          <div class="col-sm-4">
            <%= f.text_field :last_name_kana, class: "form-control" %>
          </div>
          <div class="col-sm-4">
            <%= f.text_field :first_name_kana, class: "form-control" %>
          </div>
        </div>
        <div class="row">
          <label class="col-sm-4 col-form-label"><%= f.label :郵便番号%></label>
          <div class="col-sm-4">
            <%= f.text_field :postal_code, class: "form-control" %>
          </div>
        </div>
        <div class="row">
          <label class="col-sm-4 col-form-label"><%= f.label :住所 %></label>
          <div class="col-sm-8">
            <%= f.text_field :address, class: "form-control" %>
          </div>
        </div>
        <div class="row">
          <label class="col-sm-4 col-form-label"><%= f.label :電話番号 %></label>
          <div class="col-sm-4">
            <%= f.text_field :telephone_number, class: "form-control" %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-4 col-form-label"><%= f.label :メールアドレス %></label>
          <div class="col-sm-4">
            <%= f.text_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-4">会員ステータス</label>
          <div class="col-sm-4">
            <div class="form-check form-check-inline">
              <label>
                <%= f.radio_button :is_active, :有効, class: "form-check-input" %>有効
              </label>
            </div>
            <div class="form-check form-check-inline">
              <label>
                <%= f.radio_button :is_active, :退会, class: "form-check-input" %>退会
              </lavel>
            </div>
          </div>
        </div>
        <div class="form-group text-center">
          <%= f.submit "変更を保存", class: "btn btn-success mb-2" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row mb-4">
    <h1>会員一覧</h1>
  </div>
  <div class="row">
    <div class="col">
      <table class="table table-hover">
        <thead class="thead-light">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td>
                <%= customer.id %>
              </td>
              <td>
                <%= link_to admin_customer_path(customer) do %>
                  <%= customer.last_name %><%= customer.first_name %>
                <% end %>
              </td>
              <td>
                <%= customer.email %>
              </td>
              <td>
                <%= customer.is_active %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="w-75">
    <div class="col mb-4">
      <h1>
        <%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細
      </h1>
    </div>
    <div class="col mb-4">
      <div class="row">
        <label class="col-sm-3">会員ID</label>
        <div class="col-sm-9">
          <%= @customer.id %>
        </div>
      </div>
      <div class="row">
        <label class="col-sm-3">氏名</label>
        <div class="col-sm-9">
          <%= @customer.last_name %> <%= @customer.first_name %>
        </div>
      </div>
      <div class="row">
        <label class="col-sm-3">フリガナ</label>
        <div class="col-sm-9">
          <%= @customer.last_name_kana %> <%= @customer.first_name_kana %>
        </div>
      </div>
      <div class="row">
        <label class="col-sm-3">郵便番号</label>
        <div class="col-sm-9">
          <%= @customer.postal_code %>
        </div>
      </div>
      <div class="row">
        <label class="col-sm-3">住所</label>
        <div class="col-sm-9">
          <%= @customer.address %>
        </div>
      </div>
      <div class="row">
        <label class="col-sm-3">電話番号</label>
        <div class="col-sm-9">
          <%= @customer.telephone_number %>
        </div>
      </div>
      <div class="row">
        <label class="col-sm-3">メールアドレス</label>
        <div class="col-sm-9">
          <%= @customer.email %>
        </div>
      </div>
      <div class="row">
        <label class="col-sm-3">会員ステータス</label>
        <div class="col-sm-9">
          <%= @customer.is_active %>
        </div>
      </div>
    </div>
    <div class="col text-center">
      <%= link_to edit_admin_customer_path(@customer) do %>
        <span class="btn btn-success mb-2 mr-5">編集する</span>
      <% end %>
      <%= link_to admin_root_path do %>
        <span class="btn btn-primary mb-2 ml-5">注文履歴一覧を見る</span>
      <% end %>
    </div>
  </div>
</div>