config/routes.rb
Rails.application.routes.draw do
  
  # 顧客側のパス
  devise_for :customers, path: 'customers',
  controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
    passwords: 'public/passwords'
  }
  
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    
    delete '/cart_items/all' => 'cart_items#destroy_all' # カート内商品全削除
    
    # 注文情報確認画面、注文完了画面
    get '/orders/confirm' => 'orders#confirm'
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#complete'
    
    # 情報入力画面での配送先登録用のアクション
    post '/orders/create_address' => 'orders#create_address' 
    
    # 顧客の退会確認画面、退会処理（ステータスの更新）
    get '/customers/withdrawal' => 'customers#withdrawal'
    patch '/customers/withdrawal' => 'customers#destroy'
    
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:index, :create, :new, :show]
    resources :customers, only: [:show, :edit, :update]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  end
  
  # 管理者側のパス
  devise_for :admins, path: 'admin',
  controllers: {
    sessions: 'admin/sessions',
    registration: 'admin/registrations',
    passwords: 'admin/passwords'
  }
    
  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end  
  
end

app/models/order.rb
class Order < ApplicationRecord
  
  has_many :order_details
  belongs_to :customer
  
  with_options presence: true do
    validates :customer_id
    validates :address
    validates :shipping_cost
    validates :payment
    validates :payment_method
    validates :status
  end
  
  enum status: { 入金待ち: 1, 入金確認: 2, 製作中: 3, 発送準備中: 4, 発送済み: 5}
  enum payment_method: { クレジットカード: 1, 銀行振込: 0 } # 銀行振込を2に設定するとエラーが発生するため、銀行振込を0に設定した
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @detail = @order.order_details
    @order.update(order_params)
    
    # 注文ステータスを「入金確認」にしたとき、製作ステータスが「製作待ち」に更新される処理
    if @order.status == "入金確認"
      @detail.update_all(making_status: "製作待ち")
      flash[:success] = '注文ステータス「入金確認」、製作ステータス「製作待ち」に更新しました！'
      redirect_to admin_order_path(@order)
      
    # 注文ステータスを「発送済み」にしたとき、注文ステータスが「発送済み」に更新される処理
    elsif @order.status == "発送済み"
      flash[:success] = '注文ステータスを「発送済み」に更新しました！'
      redirect_to admin_order_path(@order)
      
    # 上記2つ以外の注文ステータスを選択した場合
    else
      flash[:success] = '注文ステータスを更新しました！'
      redirect_to admin_order_path(@order)
    end  
  end

  # 注文ステータス・着手状況の更新に関するストロングパラメータ
  private

  def order_params
    params.require(:order).permit(:status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container ">
  <div class="row mb-4">
    <h1>注文履歴詳細</h1>
  </div>
  <div class="col mb-4">
    <div class="row">
      <label class="col-sm-3">購入者</label>
      <div class="col-sm-9">
        <%= link_to admin_customer_path(@order.customer_id) do %>
          <%= (@order.customer.last_name) + (@order.customer.first_name) %>
        <% end %>  
      </div>
    </div>
    <div class="row">
      <label class="col-sm-3">注文日</label>
      <div class="col-sm-9">
        <%= @order.created_at %>
      </div>
    </div>
    <div class="row">
      <label class="col-sm-3">配送先</label>
      <div class="col-sm-9">
        <%= @order.postal_code %><%= @order.address %><%= @order.name %>
      </div>
    </div>
    <div class="row">
      <label class="col-sm-3">支払方法</label>
      <div class="col-sm-9">
        <%= @order.payment_method %>
      </div>
    </div>  
    <div class="row">
      <label class="col-sm-3">注文ステータス</label>
      <div class="col-sm-9">
        <%= form_with model: @order, url: admin_order_path(@order), local: true do |f| %>
          <%= f.select :status, Order.statuses.keys.to_a, class: "form-control" %>
          <%= f.submit "更新", class: "btn btn-success" %>
        <% end %>  
      </div>  
    </div>  
  </div>
  <div class="row">
    <div class="col-sm-8">
      <table class="table table-hover">
        <thead class="thead-light">
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
            <tr>
              <td>
                <%= order_detail.item.name %>
              </td>
              <td>
                <%= (order_detail.price * 1.1).floor.to_s(:delimited) %>
              </td>
              <td>
                <%= order_detail.amount %>
              </td>
              <td>
                <%= ((order_detail.price * 1.1) * (order_detail.amount)).floor.to_s(:delimited) %>
              </td>
              <td>
                <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), local: true do |f| %>
                  <%= f.select :making_status, OrderDetail.making_statuses.keys.to_a, class: "form-control" %>
                  <%= f.submit "更新", class: "btn btn-success" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-sm-4 pull-right">
      <table class="table table-borderless">
        <tbody>
        <% %>
          <tr>
            <td>商品合計</td>
            <td><%= (@order.payment).floor.to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <td>送料</td>
            <td><%= @order.shipping_cost %>円</td>
          </tr>
          <tr>
            <td>請求金額合計</td>
            <td><%= (@order.payment + @order.shipping_cost).floor.to_s(:delimited) %> 円</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>