config/routes.rb
Rails.application.routes.draw do
  
  # 顧客側のパス
  devise_for :customers, path: 'customers',
  controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
    passwords: 'public/passwords'
  }
  
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    
    delete '/cart_items/all' => 'cart_items#destroy_all' # カート内商品全削除
    
    # 注文情報確認画面、注文完了画面
    get '/orders/confirm' => 'orders#confirm'
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#complete'
    
    # 情報入力画面での配送先登録用のアクション
    post '/orders/create_address' => 'orders#create_address' 
    
    # 顧客の退会確認画面、退会処理（ステータスの更新）
    get '/customers/withdrawal' => 'customers#withdrawal'
    patch '/customers/withdrawal' => 'customers#destroy'
    
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:index, :create, :new, :show]
    resources :customers, only: [:show, :edit, :update]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  end
  
  # 管理者側のパス
  devise_for :admins, path: 'admin',
  controllers: {
    sessions: 'admin/sessions',
    registration: 'admin/registrations',
    passwords: 'admin/passwords'
  }
    
  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end  
  
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  with_options presence: true do
    validates :customer_id
    validates :name
    validates :address
    validates :postal_code
  end
  
  composed_of :fulladdress,
    :class_name => "Fulladdress",
    :mapping => [
      [:postal_code, :postal_code],
      [:address, :address],
      [:name, :name]
    ]
end

class Fulladdress
  attr_reader :postal_code, :address, :name
  
  def initialize(postal_code, address, name)
    @postal_code = postal_code
    @address = address
    @name = name
  end
  
  def to_s
    [@postal_code, @address, @name].compact.join("")
  end
end  

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  with_options presence: true do
    validates :last_name
    validates :last_name_kana
    validates :first_name
    validates :first_name_kana
    validates :address
    validates :telephone_number
    validates :is_active
  end
  
  enum is_active: { 有効: 1, 退会: 2 }
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  
  validates :name, presence: true
  
end

app/models/item.rb
class Item < ApplicationRecord
  
  belongs_to :genre
  has_many :order_details
  has_many :cart_items
  
  with_options presence: true do
    validates :image
    validates :name
    validates :introduction
    validates :price
    validates :is_active
  end
  
  attachment :image
  enum is_active: { 販売中: 1, 販売停止中: 2 }
  
end

app/models/order.rb
class Order < ApplicationRecord
  
  has_many :order_details
  belongs_to :customer
  
  with_options presence: true do
    validates :customer_id
    validates :address
    validates :shipping_cost
    validates :payment
    validates :payment_method
    validates :status
  end
  
  enum status: { 入金待ち: 1, 入金確認: 2, 製作中: 3, 発送準備中: 4, 発送済み: 5}
  enum payment_method: { クレジットカード: 1, 銀行振込: 0 } # 銀行振込を2に設定するとエラーが発生するため、銀行振込を0に設定した
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  with_options presence: true do
    validates :order_id
    validates :item_id
    validates :price
    validates :amount
    validates :making_status
  end

  enum making_status: { 製作不可: 1, 製作待ち: 2, 製作中: 3, 製作完了: 4 }
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
    # 遷移元(直前)のcontrollerやaction名を取得する
    @path = Rails.application.routes.recognize_path(request.referer)
    
    # 顧客の会員詳細ページ(admin/customers#show)「注文履歴一覧を見る」を押した場合、その顧客の注文履歴のみ表示される
    if @path[:controller] == "admin/customers" && @path[:action] = "show"
      @customer = Customer.find_by(@path[:id])
      @orders = Order.where(customer_id: @path[:id]).page(params[:page]).reverse_order
    else
      @orders = Order.all.page(params[:page]).reverse_order
    end
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @items = Item.page(params[:page]).reverse_order
  end
  
  def new
    @item = Item.new
  end
  
  # 商品データの保存
  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = '商品データを保存しました！'
      redirect_to admin_item_path(@item)
    else
      flash[:danger] = '内容に不備があります！'
      render :new
    end  
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  # 商品データの更新
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:success] = '編集内容を保存しました！'
      redirect_to admin_item_path(@item.id)
    else
      flash[:danger] = "内容に不備があります！"
      render :edit
    end  
  end
  
  # 商品データのストロングパラメータ
  private
  
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types = :success, :info, :warning, :danger
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  # ログアウト後のパス設定
  def after_sign_out_path_for(resource)
    if resource == :admin
      flash[:success] = 'ログアウトしました！'
      new_admin_session_path
    else
      flash[:success] = 'ログアウトしました！'
      root_path
    end
  end
  
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
    keys: [
      :last_name, 
      :first_name,
      :last_name_kana,
      :first_name_kana,
      :postal_code,
      :address,
      :telephone_number,
      :is_active,
      ])
  end
end

app/controllers/concerns/accessible.rb
module Accessible
  extend ActiveSupport::Concern
  included do
    before_action :check_user
  end

  protected
  def check_user
    if current_admin
      flash.clear
      # if you have rails_admin. You can redirect anywhere really
      redirect_to(admin_root_url) and return
    elsif current_customer
      flash.clear
      # The authenticated root path can be defined in your routes.rb in: devise_for :customer do...
      redirect_to(root_path) and return
    end
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=devise-width, initial-scale=1,maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <h1 class="navbar-brand">
            <%= link_to root_path do %>
              <img class="img-responsive" src="/naganocake.jpg" height="70" width="100">
            <% end %>
          </h1>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if customer_signed_in? %>
                <li class="nav-item">
                  <strong class="text-center">ようこそ、<%= current_customer.last_name %>さん！</strong>
                </li>
                <li class="nav-item">
                  <%= link_to "マイページ", customer_path(current_customer), class: "nav-link btn btn-outline-secondary" %>
                </li>
                <li class="nav-item">
                  <%= link_to "商品一覧", items_path, class: "nav-link btn btn-outline-secondary" %>
                </li>
                <li class="nav-item">
                  <%= link_to "カート", cart_items_path, class: "nav-link btn btn-outline-secondary" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link btn btn-outline-secondary" %>
                </li>
              <% elsif admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to "商品一覧", admin_items_path, class: "nav-link btn btn-outline-secondary" %>
                </li>
                <li class="nav-item">
                  <%= link_to "会員一覧", admin_customers_path, class: "nav-link btn btn-outline-secondary" %>
                </li>
                <li class="nav-item">
                  <%= link_to "注文履歴一覧", admin_root_path, class: "nav-link btn btn-outline-secondary" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link btn btn-outline-secondary" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link btn btn-outline-secondary" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "About", about_path, class: "nav-link btn btn-outline-secondary" %>
                </li>
                <li class="nav-item">
                  <%= link_to "商品一覧", items_path, class: "nav-link btn btn-outline-secondary" %>
                </li>
                <li class="nav-item">
                  <%= link_to "新規登録", new_customer_registration_path, class: "nav-link btn btn-outline-secondary" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_customer_session_path, class: "nav-link btn btn-outline-secondary" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <!--flashによるメッセージ表示-->
      <% flash.each do |key, msg| %>
        <p class="alert alert-<%= key %>">
          <%= msg.html_safe %>
        </p>
      <% end %>
      <!----------------------------->
    </header>
    
    <main class="mt-5 mb-auto">
      <%= yield %>
    </main>
    
    <footer class="shadow-sm pt-4">
      <div class="footer border-top"></div>
    </footer>
  </body>
</html>